#!/usr/bin/env python3
"""
Script to create animated GIFs from trace plots.

This script takes the PNG images generated by plot_traces.py and combines them
into an animated GIF for a particular teaching simulation setting.
"""

import os
import glob
from jsonargparse import ArgumentParser, ActionConfigFile
from PIL import Image
from tqdm import tqdm


def create_gif_from_traces(
    trace_dir,
    plot_type,
    output_file=None,
    max_rounds=None,
    duration=500,
    loop=0,
    optimize=True,
    quality=85,
):
    """
    Create an animated GIF from trace plot images.

    Parameters
    ----------
    trace_dir : str
        Directory containing the {type}_round_*.png files.
    output_file : str, optional
        Path to save the output GIF. If None, saves as 'animation.gif' in trace_dir.
    duration : int, optional
        Duration of each frame in milliseconds (default: 500).
    loop : int, optional
        Number of times to loop the animation. 0 means infinite loop (default: 0).
    optimize : bool, optional
        Whether to optimize the GIF file size (default: True).
    quality : int, optional
        Quality of the GIF (1-100). Lower values reduce file size (default: 85).
    """
    # Find all trace round images
    trace_files = os.listdir(trace_dir)
    trace_files = [
        f
        for f in trace_files
        if f.startswith(f"{plot_type}_round_") and f.endswith(".png")
    ]
    trace_files = [os.path.join(trace_dir, f) for f in trace_files]
    trace_files.sort(
        key=lambda x: int(os.path.splitext(os.path.basename(x))[0].split("_")[-1])
    )

    # Limit to max_rounds if specified
    if max_rounds is not None:
        trace_files = trace_files[:max_rounds]

    if not trace_files:
        print(f"Error: No {plot_type}_round_*.png files found in {trace_dir}")
        return False

    print(f"Found {len(trace_files)} trace images in {trace_dir}")

    # Set output file
    if output_file is None:
        output_file = os.path.join(trace_dir, "animation.gif")
    else:
        output_file = os.path.join(trace_dir, output_file)

    # Load images
    print("Loading images...")
    images = []
    for trace_file in tqdm(trace_files, desc="Loading"):
        img = Image.open(trace_file)
        # Convert to RGB if necessary (GIF doesn't support RGBA)
        if img.mode == "RGBA":
            # Create a white background
            background = Image.new("RGB", img.size, (255, 255, 255))
            background.paste(img, mask=img.split()[3])  # Use alpha channel as mask
            img = background
        elif img.mode != "RGB":
            img = img.convert("RGB")
        images.append(img)

    # Save as GIF
    print(f"Creating GIF: {output_file}")
    images[0].save(
        output_file,
        save_all=True,
        append_images=images[1:],
        duration=duration,
        loop=loop,
        optimize=optimize,
        quality=quality,
    )

    # Get file size
    file_size = os.path.getsize(output_file)
    file_size_mb = file_size / (1024 * 1024)
    print(f"✓ GIF created successfully!")
    print(f"  Output: {output_file}")
    print(f"  Frames: {len(images)}")
    print(f"  Duration: {duration}ms per frame")
    print(f"  File size: {file_size_mb:.2f} MB")

    return True


def find_trace_directories(base_dir="traces", plot_type="trace"):
    """
    Find all trace directories in the base directory.

    Parameters
    ----------
    base_dir : str
        Base directory to search for trace folders (default: 'traces').

    Returns
    -------
    list
        List of trace directory paths.
    """
    trace_dirs = []
    if not os.path.exists(base_dir):
        return trace_dirs

    for item in os.listdir(base_dir):
        item_path = os.path.join(base_dir, item)
        if os.path.isdir(item_path) and not item.startswith("."):
            # Check if it contains trace files
            trace_files = glob.glob(os.path.join(item_path, f"{plot_type}_round_*.png"))
            if trace_files:
                trace_dirs.append(item_path)

    return sorted(trace_dirs)


def main():
    parser = ArgumentParser(
        description="Create animated GIF from teaching simulation trace plots"
    )
    parser.add_argument("--config", action=ActionConfigFile)
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument(
        "--n_hypotheses", type=int, default=2, help="Number of hypotheses"
    )
    parser.add_argument(
        "--n_clusters", type=int, default=2, help="Number of clusters per hypothesis"
    )
    parser.add_argument("--n_features", type=int, default=2, help="Number of features")
    parser.add_argument("--n_samples", type=int, default=100, help="Number of samples")
    parser.add_argument(
        "--n_rounds", type=int, default=100, help="Number of simulation rounds"
    )
    parser.add_argument(
        "--data_initialization",
        type=str,
        default="normal",
        choices=["uniform", "normal"],
        help="Data initialization method",
    )
    parser.add_argument(
        "--interaction_mode",
        type=str,
        default="lazy_student",
        choices=["active_interaction", "lazy_student", "lazy_teacher"],
        help="Interaction mode between teacher and student",
    )
    parser.add_argument(
        "--teacher_strategy",
        type=str,
        default="hypothesis",
        choices=["random", "hypothesis"],
        help="Teacher strategy to select data points",
    )
    parser.add_argument(
        "--teacher_alpha", type=float, default=1.0, help="Teacher alpha parameter"
    )
    parser.add_argument(
        "--teacher_n_beliefs", type=int, default=100, help="Number of teacher beliefs"
    )
    parser.add_argument(
        "--teacher_student_strategy_assumption",
        type=str,
        default="",
        choices=["", "random", "uncertainty", "hypothesis"],
        help="Teacher assumption about student strategy for querying data points",
    )
    parser.add_argument(
        "--teacher_student_mode_assumption",
        type=str,
        default="naive",
        choices=["rational", "naive"],
        help="Teacher assumption about student mode",
    )
    parser.add_argument(
        "--student_mode",
        type=str,
        default="naive",
        choices=["rational", "naive"],
        help="Student mode",
    )
    parser.add_argument(
        "--student_strategy",
        type=str,
        default="",
        choices=["", "random", "uncertainty", "hypothesis"],
        help="Student strategy for querying data points",
    )
    parser.add_argument(
        "--student_beta", type=float, default=1.0, help="Student beta parameter"
    )
    parser.add_argument(
        "--student_teacher_strategy_assumption",
        type=str,
        default="",
        choices=["", "random", "hypothesis"],
        help="Student assumption about teacher strategy to select data points",
    )
    parser.add_argument(
        "--max_rounds",
        type=int,
        default=None,
        help="Maximum number of rounds to plot (default: all)",
    )
    parser.add_argument(
        "--type",
        type=str,
        default="trace",
        choices=["trace", "teacher_belief"],
        help="Type of the output GIF (default: trace)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output GIF file path (default: animation.gif in trace directory)",
    )
    parser.add_argument(
        "--duration",
        type=int,
        default=500,
        help="Duration of each frame in milliseconds (default: 500)",
    )
    parser.add_argument(
        "--loop",
        type=int,
        default=0,
        help="Number of times to loop (0 = infinite, default: 0)",
    )
    parser.add_argument(
        "--no-optimize",
        action="store_true",
        help="Disable GIF optimization (results in larger file size)",
    )
    parser.add_argument(
        "--quality",
        type=int,
        default=100,
        help="GIF quality (1-100, default: 100)",
    )
    parser.add_argument(
        "--base_dir",
        type=str,
        default="traces",
        help="Base directory to search for trace folders (default: traces)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Create GIFs for all trace directories found in base_dir",
    )

    args = parser.parse_args()

    # Process all directories
    if args.all:
        trace_dirs = find_trace_directories(args.base_dir, plot_type=args.type)
        if not trace_dirs:
            print(f"Error: No {args.type} directories found in '{args.base_dir}'")
            return

        print(f"Found {len(trace_dirs)} {args.type} directories\n")
        success_count = 0

        for i, trace_dir in enumerate(trace_dirs, 1):
            print(f"\n[{i}/{len(trace_dirs)}] Processing: {trace_dir}")
            print("-" * 80)
            success = create_gif_from_traces(
                trace_dir=trace_dir,
                plot_type=args.type,
                output_file=args.output,
                max_rounds=args.max_rounds,
                duration=args.duration,
                loop=args.loop,
                optimize=not args.no_optimize,
                quality=args.quality,
            )
            if success:
                success_count += 1

        print(f"\n{'=' * 80}")
        print(f"Summary: Created {success_count}/{len(trace_dirs)} GIFs successfully")

    # Process single directory
    else:
        trace_dir = os.path.join(
            "traces",
            f"seed{args.seed}_"
            f"{'lazy' if args.interaction_mode == 'lazy_teacher' else ''}"
            f"teach[{args.teacher_strategy}-{args.teacher_alpha}-{args.teacher_n_beliefs}-"
            f"{args.teacher_student_mode_assumption}-{args.teacher_student_strategy_assumption}]_"
            f"{'lazy' if args.interaction_mode == 'lazy_student' else ''}"
            f"stud[{args.student_mode}-{args.student_strategy}-{args.student_beta}-"
            f"{args.student_teacher_strategy_assumption}]",
        )

        if not os.path.isdir(trace_dir):
            print(f"Error: Directory not found: {trace_dir}")
            return

        create_gif_from_traces(
            trace_dir=trace_dir,
            plot_type=args.type,
            output_file=args.output,
            max_rounds=args.max_rounds,
            duration=args.duration,
            loop=args.loop,
            optimize=not args.no_optimize,
            quality=args.quality,
        )


if __name__ == "__main__":
    main()
