n_hypotheses: 10
n_clusters: 2
n_features: 2
n_samples: 50
data_initialization: uniform
teacher_strategy: hypothesis
teacher_n_beliefs: 10
teacher_alpha: 1.0
teacher_student_mode_assumption: naive
teacher_student_strategy_assumption: uncertainty
student_beta: 1.0
student_mode: rational
student_strategy: uncertainty
student_teacher_strategy_assumption: hypothesis