program: main.py
project: teachsim
method: grid
metric:
    goal: maximize
    name: true_belief_prob
parameters:
    seed: 
        values: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]
    config: 
        values: [
            # Small scale
            configs/exp1.1.yaml,
            configs/exp1.2.yaml,
            configs/exp1.3.yaml,
            configs/exp1.4_2.1.yaml,
            configs/exp1.5.yaml,
            configs/exp1.6.yaml,
            configs/exp1.7.yaml,
            configs/exp1.8_2.2_3.3_4.1_5.1_6.1.yaml,
            configs/exp1.9.yaml,
            configs/exp1.10.yaml,
            configs/exp3.1.yaml,
            configs/exp3.2.yaml,
            configs/exp4.2.yaml,
            configs/exp4.3.yaml,
            configs/exp4.4.yaml,
            configs/exp5.2.yaml,
            configs/exp5.3.yaml,
            configs/exp6.2.yaml,
            configs/exp6.3.yaml,
            # Medium scale
            configs/exp1.1_m.yaml,
            configs/exp1.2_m.yaml,
            configs/exp1.3_m.yaml,
            configs/exp1.4_2.1_m.yaml,
            configs/exp1.5_m.yaml,
            configs/exp1.6_m.yaml,
            configs/exp1.7_m.yaml,
            configs/exp1.8_2.2_3.3_4.1_5.1_m.yaml,
            configs/exp1.9_m.yaml,
            configs/exp1.10_m.yaml,
            configs/exp3.1_m.yaml,
            configs/exp3.2_m.yaml,
            configs/exp4.2_m.yaml,
            configs/exp4.3_m.yaml,
            configs/exp4.4_m.yaml,
            configs/exp5.2_m.yaml,
            configs/exp5.3_m.yaml,
            # Large scale
            configs/exp1.1_d.yaml,
            configs/exp1.2_d.yaml,
            configs/exp1.3_d.yaml,
            configs/exp1.4_2.1_d.yaml,
            configs/exp1.5_d.yaml,
            configs/exp1.6_d.yaml,
            configs/exp1.7_d.yaml,
            configs/exp1.8_2.2_3.3_4.1_5.1_d.yaml,
            configs/exp1.9_d.yaml,
            configs/exp1.10_d.yaml,
            configs/exp3.1_d.yaml,
            configs/exp3.2_d.yaml,
            configs/exp4.2_d.yaml,
            configs/exp4.3_d.yaml,
            configs/exp4.4_d.yaml,
            configs/exp5.2_d.yaml,
            configs/exp5.3_d.yaml,
        ]