program: main.py
project: teachsim
method: grid
metric:
    goal: maximize
    name: true_belief_prob
parameters:
    seed: 
        values: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]
    config: 
        values: [
            configs/exp1.1.yaml,
            configs/exp1.2_2.2_3.3_4.1_5.2_6.3_7.4.yaml,
            configs/exp2.1.yaml,
            configs/exp3.1.yaml,
            configs/exp3.2.yaml,
            configs/exp3.4.yaml,
            configs/exp4.2.yaml,
            configs/exp4.3.yaml,
            configs/exp4.4.yaml,
            configs/exp5.1.yaml,
            configs/exp5.3.yaml,
            configs/exp6.1.yaml,
            configs/exp6.2.yaml,
            configs/exp7.1.yaml,
            configs/exp7.2.yaml,
            configs/exp7.3.yaml,
        ]